[package]
name = "synthesizer-io-core"
version = "0.1.0"
license = "Apache-2.0"
authors = ["Raph Levien <raph@google.com>"]
description = "Computational core for sound synthesis."

[dependencies]
lazy_static = "1.0"
